### ISSUE TITLE
Something is giving marines cellular damage

### ISSUE THREAD

**Issue by Skarletto** [CM-14/CM-14#2364]
## Description

Not treatable unless your doctor makes phalanximine. Multiple marines had it.

**Comment by QuietlyWhisper** [comment]
There doesn't appear to be any sources of cellular damage in cm besides eating someone's brain, however I think this came up because we had admins removing rotting comp so people could be revived, but didn't remember that rotting bodies accumulate cellular damage

If this happens again in the next playtest and it wasn't due to revival we can reopen this issue
